<?php
/**
 * Callback function to create custom metaboxes of the cpt Branch with the Metabox.io plugin
 *
 * @param [type] $meta_boxes
 * @return void
 */
function branch_register_meta_box($meta_boxes){
    $prefix = 'branch_';

    $meta_boxes[] = [
        'title' => esc_html__('Dati Filiale', 'wordpress-csp'),
        'id' => 'branch_fields',
        'context' => 'normal',
        'post_types' => 'branch',
        'fields' => [
            [
                'type'          => 'text',
                'name'          => esc_html__('Cittá', 'wordpress-csp'),
                'id'            => $prefix . 'city',
                'placeholder'   => esc_html__('Inserisci la cittá della filiale', 'wordpress-csp'),
            ],
            [
                'type'          => 'text',
                'name'          => esc_html__('Indirizzo', 'wordpress-csp'),
                'id'            => $prefix . 'address',
                'sanitize_callback' => 'none',
                'placeholder'   => esc_html__('Inserisci la sede della filiale', 'wordpress-csp'),
            ],
            [
                'type'              => 'select',
                'multiple'          => false,
                'select_all_none'   => false,
                'name'              => esc_html__('Provincia', 'wordpress-csp'),
                'id'                => $prefix . 'country',
                'desc'              => esc_html__('Seleziona la provincia della filiale', 'wordpress-csp'),
                'options'           => [
                        'AG' => 'Agrigento',
                        'AL' => 'Alessandria',
                        'AN' => 'Ancona',
                        'AO' => 'Aosta',
                        'AR' => 'Arezzo',
                        'AP' => 'Ascoli Piceno',
                        'AT' => 'Asti',
                        'AV' => 'Avellino',
                        'BA' => 'Bari',
                        'BT' => 'Barletta-Andria-Trani',
                        'BL' => 'Belluno',
                        'BN' => 'Benevento',
                        'BG' => 'Bergamo',
                        'BI' => 'Biella',
                        'BO' => 'Bologna',
                        'BZ' => 'Bolzano',
                        'BS' => 'Brescia',
                        'BR' => 'Brindisi',
                        'CA' => 'Cagliari',
                        'CL' => 'Caltanissetta',
                        'CB' => 'Campobasso',
                        'CE' => 'Caserta',
                        'CT' => 'Catania',
                        'CZ' => 'Catanzaro',
                        'CH' => 'Chieti',
                        'CO' => 'Como',
                        'CS' => 'Cosenza',
                        'CR' => 'Cremona',
                        'KR' => 'Crotone',
                        'CN' => 'Cuneo',
                        'EN' => 'Enna',
                        'FM' => 'Fermo',
                        'FE' => 'Ferrara',
                        'FI' => 'Firenze',
                        'FG' => 'Foggia',
                        'FC' => 'Forlì-Cesena',
                        'FR' => 'Frosinone',
                        'GE' => 'Genova',
                        'GO' => 'Gorizia',
                        'GR' => 'Grosseto',
                        'IM' => 'Imperia',
                        'IS' => 'Isernia',
                        'SP' => 'La Spezia',
                        'AQ' => 'L\'Aquila',
                        'LT' => 'Latina',
                        'LE' => 'Lecce',
                        'LC' => 'Lecco',
                        'LI' => 'Livorno',
                        'LO' => 'Lodi',
                        'LU' => 'Lucca',
                        'MC' => 'Macerata',
                        'MN' => 'Mantova',
                        'MS' => 'Massa-Carrara',
                        'MT' => 'Matera',
                        'ME' => 'Messina',
                        'MI' => 'Milano',
                        'MO' => 'Modena',
                        'MB' => 'Monza e della Brianza',
                        'NA' => 'Napoli',
                        'NO' => 'Novara',
                        'NU' => 'Nuoro',
                        'OR' => 'Oristano',
                        'PD' => 'Padova',
                        'PA' => 'Palermo',
                        'PR' => 'Parma',
                        'PV' => 'Pavia',
                        'PG' => 'Perugia',
                        'PU' => 'Pesaro e Urbino',
                        'PE' => 'Pescara',
                        'PC' => 'Piacenza',
                        'PI' => 'Pisa',
                        'PT' => 'Pistoia',
                        'PN' => 'Pordenone',
                        'PZ' => 'Potenza',
                        'PO' => 'Prato',
                        'RG' => 'Ragusa',
                        'RA' => 'Ravenna',
                        'RC' => 'Reggio Calabria',
                        'RE' => 'Reggio Emilia',
                        'RI' => 'Rieti',
                        'RN' => 'Rimini',
                        'RM' => 'Roma',
                        'RO' => 'Rovigo',
                        'SA' => 'Salerno',
                        'SS' => 'Sassari',
                        'SV' => 'Savona',
                        'SI' => 'Siena',
                        'SR' => 'Siracusa',
                        'SO' => 'Sondrio',
                        'SU' => 'Sud Sardegna',
                        'TA' => 'Taranto',
                        'TE' => 'Teramo',
                        'TR' => 'Terni',
                        'TO' => 'Torino',
                        'TP' => 'Trapani',
                        'TN' => 'Trento',
                        'TV' => 'Treviso',
                        'TS' => 'Trieste',
                        'UD' => 'Udine',
                        'VA' => 'Varese',
                        'VE' => 'Venezia',
                        'VB' => 'Verbano-Cusio-Ossola',
                        'VC' => 'Vercelli',
                        'VR' => 'Verona',
                        'VV' => 'Vibo Valentia',
                        'VI' => 'Vicenza',
                        'VT' => 'Viterbo',
                    ],
            ],
            [
                'type'          => 'text',
                'name'          => esc_html__('Cap', 'wordpress-csp'),
                'id'            => $prefix . 'cap',
                'placeholder'   => esc_html__('Inserisci il cap della filiale', 'wordpress-csp'),
            ],
            [
                'type'          => 'text',
                'name'          => esc_html__('Numero telefono', 'wordpress-csp'),
                'id'            => $prefix . 'phone_number',
                'sanitize_callback' => 'none',
                'placeholder'   => esc_html__('Inserisci il numero di telefono della filiale', 'wordpress-csp'),
            ],
            [
                'type'          => 'text',
                'name'          => esc_html__('Email', 'wordpress-csp'),
                'id'            => $prefix . 'email',
                'sanitize_callback' => 'none',
                'placeholder'   => esc_html__('Inserisci la mail della filiale', 'wordpress-csp'),
            ],
            [
                'type'          => 'textarea',
                'name'          => esc_html__('Orari d\'apertura', 'wordpress-csp'),
                'id'            => $prefix . 'time',
                'sanitize_callback' => 'none',
                'rows'          => 5,
                'placeholder'   => esc_html__('Inserisci l\'orario di apertura della filiale', 'wordpress-csp'),
            ],
            [
                'type'          => 'textarea',
                'name'          => esc_html__('Google maps', 'wordpress-csp'),
                'id'            => $prefix . 'map',
                'sanitize_callback' => 'none',
                'rows'          => 5,
                'placeholder'   => esc_html__('Inserisci l\'iframe di Google Map della filiale', 'wordpress-csp'),
            ]
        ],

    ];

    return $meta_boxes;
}
add_filter('rwmb_meta_boxes', 'branch_register_meta_box');
